[custom]
;poorcar

ruleset=🎯 全球直连,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/ChinaMedia.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Telegram.list
ruleset=📹 Youtube,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Youtube.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/TikTok.list
ruleset=📟 Twitter,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Twitter.list
ruleset=🍪 动漫疯,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Bahamut.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Netflix.list
ruleset=💿 Spotify,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Spotify.list
ruleset=🤖 OpenAI,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/OpenAI.list
ruleset=🤖 Gemini,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Gemini.list
ruleset=🤖 Claude,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Claude.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/GoogleFCM.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Apple.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/ProxyMedia.list
ruleset=📀 EMBY影视,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/Emby.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/ptDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/a214955582/ACL4SSR/refs/heads/main/Clash/poorcar/ptTracker.list
ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


custom_proxy_group=🔰 节点选择`select`[]♻️ 自动选择`[]🎯 全球直连`[]☁️ 美国`[]☁️ 新加坡`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=📲 Telegram`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📹 Youtube`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🎵 TikTok`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📟 Twitter`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🍪 动漫疯`select`[]🔰 节点选择`[]🎯 全球直连`(动漫疯|巴哈|香港|台湾)
custom_proxy_group=🎥 Netflix`select`[]🔰 节点选择`[]🎯 全球直连`.*`(NF|奈飞|解锁|Netflix|NETFLIX|Media|MITM)
custom_proxy_group=💿 Spotify`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🤖 OpenAI`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🤖 Gemini`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🤖 Claude`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📢 谷歌FCM`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🔰 节点选择`.*
custom_proxy_group=🍎 苹果服务`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🌍 国外媒体`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=☁️ 美国`url-test`(美国)`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=☁️ 新加坡`url-test`(新加坡)`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=📀 EMBY影视`select`[]🔰 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🔰 节点选择`[]🎯 全球直连`[]♻️ 自动选择`.*


enable_rule_generator=true
overwrite_original_rules=true
